//Helper function to convert blob to base64
function blobToBase64(blob) {
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result);
    reader.readAsDataURL(blob);
  });
}

//Renders the shop list
function renderShopList() {
  const list = document.getElementById("shopList");
  list.innerHTML = "";

  for (const merchant of merchants){
    const li = document.createElement("li");
    li.textContent = `${merchant.name} - ${merchant.type}`;
    li.addEventListener("click", () => merchant.render());
    list.appendChild(li);
  }
}

//Generates all the shops
async function generateShops() {
  //mmmm the Throbber
  document.getElementById("loadingSpinner").style.display = "block";

  let last_promise;
  for (const merchant of merchants) {
    let set_inventory = () => merchant.setInventory();
    last_promise = merchant.loadItems().then(set_inventory);
  }
  await last_promise;

  renderShopList();
  document.getElementById("shopName").innerText  = "Select a Shopkeeper";
  document.getElementById("shopLore").innerText  = "";
  document.getElementById("shopItems").innerHTML = "";
  
  //Throb B Gone
  document.getElementById("loadingSpinner").style.display = "none";
  document.getElementById("saveBtn").disabled = false;
  document.getElementById("exportBtn").disabled = false;
}

//Downloads the inventories of all the merchants
function saveInventories() {
  const data = merchants.map(merchant => ({
    name: merchant.name,
    type: merchant.type,
    lore: merchant.lore,
    merchant_luck: merchant.merchantLuck,
    table_name: merchant.table_name,
    inventory: merchant.inventory
  }));
  
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `shop_inventories_${Date.now()}.json`;
  link.click();
  
  URL.revokeObjectURL(url);
  console.log("Inventories saved!");
}

//Exports a standalone HTML file for players (This part was entirely generated by AI. If it breaks or need to be modified... may Claude have mercy on your soul)
async function exportPlayerHTML() {
  const timestamp = Date.now();
  
  // Convert cursor images to base64
  const cursorImages = {};
  try {
    const scrollCursor = await fetch('icons/scroll-cursor.png').then(r => r.blob());
    const swordCursor = await fetch('icons/sword-cursor.png').then(r => r.blob());
    const clickableCursor = await fetch('icons/sword-cursor-clickable.png').then(r => r.blob());
    const favicon = await fetch('icons/favicon.png').then(r => r.blob());
    
    cursorImages.scroll = await blobToBase64(scrollCursor);
    cursorImages.sword = await blobToBase64(swordCursor);
    cursorImages.clickable = await blobToBase64(clickableCursor);
    cursorImages.favicon = await blobToBase64(favicon);
  } catch(e) {
    console.warn('Could not load cursor images, using default cursors', e);
  }

  // Generate merchant data as JavaScript object
  // Helper function to convert blob to base64
  function blobToBase64(blob) {
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.readAsDataURL(blob);
    });
  }
  
  // Generate merchant data
  const merchantData = merchants.map(merchant => ({
    name: merchant.name,
    type: merchant.type,
    lore: merchant.lore,
    inventory: merchant.inventory
  }));
  

  const html = `<!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>D&D Shop Browser</title>
      ${cursorImages.favicon ? `<link rel="icon" href="${cursorImages.favicon}" type="image/png">` : ''}
      <style>
    /* ==================== RESET & BASE ==================== */
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      cursor: url('${cursorImages.sword}'), auto;
    }

    /* ==================== LAYOUT ==================== */
    #container {
      display: flex;
      height: 100vh;
      font-family: 'Georgia', serif;
      background: #f5f0e6;
    }

    /* ==================== SIDEBAR ==================== */
    #sidebar {
      width: 250px;
      background: #fdf5e6;
      border-right: 4px solid #d2b48c;
      padding: 1rem;
      display: flex;
      flex-direction: column;
      overflow-y: auto;
    }

    #shopList {
      list-style: none;
    }

    #shopList li {
      padding: 0.5rem;
      margin-bottom: 0.3rem;
      cursor: url('${cursorImages.clickable}'), auto;
      border-left: 3px solid #d2b48c;
      background: rgba(210, 180, 140, 0.2);
      transition: background 0.2s;
    }

    #shopList li:hover {
      background: rgba(210, 180, 140, 0.4);
    }

    /* ==================== MAIN CONTENT ==================== */
    #mainContent {
      flex-grow: 1;
      padding: 2rem;
      overflow-y: auto;
    }

    #shopName {
      margin-top: 0;
      margin-bottom: 0;
      color: #5a3e1b;
      text-align: center;
    }

    #shopLore {
      margin-top: 0;
      margin-bottom: 2rem;
      color: #5a3e1b;
      text-align: center;
      font-style: italic;
    }

    /* ==================== INVENTORY SECTIONS ==================== */
    .sectionHeader {
      margin-top: 1.5rem;
      margin-bottom: 0.75rem;
      color: #5a3e1b;
      font-size: 1.2rem;
      border-bottom: 2px solid #d2b48c;
      border-radius: 4px;
      padding-bottom: 0.3rem;
    }

    .sectionHeader:first-of-type {
      margin-top: 0;
    }

    .sectionHeader.special-section {
      color: #7b3f00;
      border-bottom: 2px solid #b8860b;
      padding: 0.5rem;
      border-radius: 4px;
      position: relative;
      overflow: hidden;
    }

    .sectionHeader.special-section::before {
      content: '';
      position: absolute;
      top: 0;
      left: -200%;
      width: 200%;
      height: 100%;
      background: linear-gradient(
        140deg,
        transparent,
        rgba(255, 215, 0, 0.4),
        transparent
      );
      animation: shimmer 4s infinite;
    }

    @keyframes shimmer {
      0% { left: -200%; }
      100% { left: 200%; }
    }

    .sectionContainer {
      margin-top: 1rem;
      margin-bottom: 3rem;
      background-color: #dfa87e46;
      padding: 0.5rem 0.75rem;
      border-radius: 12px;
    }

    .item-header {
      display: grid;
      grid-template-columns: 2fr 1.5fr 1fr 1fr;
      gap: 1rem;
      padding: 0.5rem 0.75rem;
      margin-top: 0.25rem;
      margin-bottom: 0.5rem;
      font-weight: bold;
      color: #5a3e1b;
      background: transparent;
    }

    /* ==================== SHOP ITEMS ==================== */
    .shopItem {
      position: relative;
      display: grid;
      grid-template-columns: 2fr 1.5fr 1fr 1fr;
      gap: 1rem;
      align-items: center;
      padding: 0.5rem 0.75rem;
      margin-bottom: 0.5rem;
      border-left: 3px solid #d2b48c;
      background: rgba(210, 180, 140, 0.39);
      border-radius: 4px;
      transition: background 0.2s;
    }
    .shopItem, .item-name, .item-type, .item-rarity, .item-value {
      cursor: url('${cursorImages.scroll}'), pointer;
    }

    .shopItem:hover {
      background: rgba(210, 180, 140, 0.35);
    }

    .item-name {
      font-weight: bold;
      color: #5a3e1b;
    }

    .item-type {
      color: #6b4e2b;
      font-style: italic;
    }

    .item-rarity {
      color: #8b5e3c;
      text-transform: capitalize;
    }

    .item-value {
      color: #5a3e1b;
      text-align: right;
      font-weight: 500;
    }

    /* ==================== TOOLTIPS ==================== */
    .shopItem .tooltiptext {
      visibility: hidden;
      max-width: 300px;
      background-color: #8b5e3c;
      color: #fdf5e6;
      font-size: 0.9rem;
      text-align: center;
      padding: 6px 8px;
      border-radius: 6px;
      box-shadow: 0 2px 6px rgba(0, 0, 0, 0.2);
      position: absolute;
      z-index: 1;
      bottom: 125%;
      left: 50%;
      transform: translateX(-50%);
      opacity: 0;
      transition: opacity 0.3s, bottom 0.3s, top 0.3s;
      white-space: normal;
      word-wrap: break-word;
    }

    .shopItem .tooltiptext::after {
      content: "";
      position: absolute;
      top: 100%;
      left: 50%;
      transform: translateX(-50%);
      border-width: 6px;
      border-style: solid;
      border-color: #8b5e3c transparent transparent transparent;
    }

    .shopItem:hover .tooltiptext {
      visibility: visible;
      opacity: 1;
      bottom: 135%;
    }

    .shopItem .tooltiptext.tooltip-flipped {
      top: 125%;
      bottom: auto;
    }

    .shopItem .tooltiptext.tooltip-flipped::after {
      content: "";
      position: absolute;
      bottom: 100%;
      top: auto;
      left: 50%;
      transform: translateX(-50%);
      border-width: 0 6px 6px 6px;
      border-style: solid;
      border-color: transparent transparent #8b5e3c transparent;
    }
      </style>
    </head>
    <body>
      <div id="container">
        <aside id="sidebar">
          <h3>Shopkeepers</h3>
          <ul id="shopList"></ul>
        </aside>
        
        <main id="mainContent">
          <h2 id="shopName">Select a Shopkeeper</h2>
          <h3 id="shopLore"></h3>
          <div id="shopItems"></div>
        </main>
      </div>

      <script>
        const merchantData = ${JSON.stringify(merchantData, null, 2)};
        
        function genItemDiv(item, sectionConfig) {
          const div = document.createElement("div");
          div.className = "shopItem";

          const name_col = document.createElement("span");
          name_col.className = "item-name";
          if (item.Attunement === "requires attunement")
            name_col.textContent = item.Name + " (A)";
          else
            name_col.textContent = item.Name;

          const type_col = document.createElement("span");
          type_col.className = "item-type";
          type_col.textContent = item.Type || "(BUG) No specified type";

          const rarity_col = document.createElement("span");
          rarity_col.className = "item-rarity";
          rarity_col.textContent = item.Rarity === "none" ? "Mundane" : item.Rarity;

          const value_col = document.createElement("span");
          value_col.className = "item-value";
          value_col.textContent = item.Value || "(BUG) No monetary value";

          div.appendChild(name_col);
          div.appendChild(type_col);
          div.appendChild(rarity_col);
          div.appendChild(value_col);

          if (item.Text && item.Text !== "") {
            const tooltip = document.createElement("span");
            tooltip.className = "tooltiptext";
            tooltip.textContent = item.Text;
            div.appendChild(tooltip);

            div.addEventListener('mouseenter', () => {
              const rect = tooltip.getBoundingClientRect();
              if (rect.top < 0) {
                tooltip.style.top = '125%';
                tooltip.style.bottom = 'auto';
                tooltip.classList.add('tooltip-flipped');
              }
            });
            div.addEventListener('mouseleave', () => {
              tooltip.style.bottom = '125%';
              tooltip.style.top = 'auto';
              tooltip.classList.remove('tooltip-flipped');
            });
          }

          return div;
        }

        function renderMerchant(merchant) {
          document.getElementById("shopName").innerText = merchant.name;
          document.getElementById("shopLore").innerText = merchant.lore;

          const items_div = document.getElementById("shopItems");
          items_div.innerHTML = "";

          for (const sectionName in merchant.inventory) {
            const items = merchant.inventory[sectionName];
            if (items.length === 0) continue;

            const sectionHeader = document.createElement("h3");
            sectionHeader.className = "sectionHeader";
            
            // Check if this section is special (contains "Special", "Find", or "Day")
            const isSpecial = sectionName.toLowerCase().includes('special') || 
                            sectionName.toLowerCase().includes('find') ||
                            sectionName.toLowerCase().includes('day');
            
            if (isSpecial) {
              sectionHeader.classList.add("special-section");
            }
            sectionHeader.textContent = sectionName;
            items_div.appendChild(sectionHeader);

            const sectionContainer = document.createElement("div");
            sectionContainer.className = "sectionContainer";

            const headerRow = document.createElement("div");
            headerRow.className = "item-header";
            headerRow.innerHTML = \`
              <span>Name</span>
              <span>Type</span>
              <span>Rarity</span>
              <span>Value</span>\`;
            sectionContainer.appendChild(headerRow);

            for (const item of items) {
              sectionContainer.appendChild(genItemDiv(item, { special: isSpecial }));
            }
            items_div.appendChild(sectionContainer);
          }
        }

        function initShopList() {
          const list = document.getElementById("shopList");
          list.innerHTML = "";

          for (const merchant of merchantData) {
            const li = document.createElement("li");
            li.textContent = \`\${merchant.name} - \${merchant.type}\`;
            li.addEventListener("click", () => renderMerchant(merchant));
            list.appendChild(li);
          }
        }

        // Initialize on load
        initShopList();
      </script>
    </body>
    </html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `dnd_shops_${timestamp}.html`;
  link.click();
  
  URL.revokeObjectURL(url);
  console.log("Player HTML exported!");
}